Fixes #19 Fixes #72 duplicate subject header on windows
laminas/laminas-mail pull request #103
Opened 2020-08-05 16:24 UTC by samsonasik

Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Re-create https://github.com/zendframework/zend-mail/pull/225 by @arueckauer Fixes #19 #72 . Original issue description reported by @matbech : 

```
Summary
On Windows with PHP 7, when sending an mail message with the Sendmail transport, the subject header is duplicated.

Steps to reproduce
To reproduce the bug the sample from here can be used:
http://framework.zend.com/manual/current/en/modules/zend.mail.introduction.html

The resulting mail headers look something like this:
Subject: Test Subject
Date: Wed, 29 Jul 2015 17:33:17 +0000
From: =?UTF-8?Q?test?= test@test.com
To: test@test.com
Subject: Test Subject

Cause
In the Sendmail transport all headers (including the Subject) and the subject itself are passed to the php mail function:
$result = mail($to, $subject, $message, $headers);
The mail function then appends to the $subject to the $headers. I do not think the php mail function should handle this case because it doesn't know what subject the caller intended to use. However I believe php mail should at least issue a warning (TBD: file enhancement at https://bugs.php.net/).
```

2020-08-05 20:10 UTC, weierophinney requested changes

2020-08-05 20:10 UTC, weierophinney commented on test/Transport/SendmailTest.php
> +        );
This is not the scenario indicated in the original report.

The original report was indicating that the **entire** subject header was being emitted _twice_ in the headers, not that the subject header **value** was being duplicated. The reporter observed the following output:

```text
Subject: Greetings and Salutations!
To: matthew@example.org
From: ralph@example.org
Subject: Greetings and Salutations!
```

Further, their assertion was that this was due to the fact that `mail()` was being called with a subject, and the underlying library emitting a subject header from that value _as well as_ emitting the one in the `$additional_headers` argument in that function.

Change the above to:

```php
$this->assertNotRegExp('/^Subject: Greetings and Salutations\!$/m', $this->additional_headers);
```

The "m" PCRE modifier will test each _line_ of the text against the regexp, allowing you to use normal start-of-line/end-of-line anchors - and you can thus ignore linebreaks, making the comparison simpler!

2020-08-05 20:14 UTC, weierophinney commented on test/Transport/SendmailTest.php
> +        );
Also, technically the `To` header will not be present in the additional headers, as we strip it to pass as a `mail()` argument; as such, you'll also have:

```php
$this->assertNotRegExp('/^To: matthew\@example\.org$/m', $this->additional_headers);
```

2020-08-05 20:55 UTC, samsonasik commented on test/Transport/SendmailTest.php
> +        );
@weierophinney updated.

2020-08-06 11:47 UTC, glensc commented on test/Transport/SendmailTest.php
> +        $this->assertNotRegExp('/^Subject: Greetings and Salutations\!$/m', $this->additional_headers);
`!` does not need to be escaped\!

`
        $this->assertNotRegExp('/^Subject: Greetings and Salutations!$/m', $this->additional_headers);
`

2020-08-06 11:48 UTC, glensc commented on test/Transport/SendmailTest.php
> +    public function isWindows()
`    private function isWindows()
`

do not export as public if not needed

2020-08-06 11:50 UTC, glensc commented on test/Transport/SendmailTest.php
> +        $lineBreak = $this->isWindows() ? "\r\n" : "\n";
drop unused `$lineBreak` variable.

2020-08-06 11:50 UTC, glensc commented on test/Transport/SendmailTest.php
> +     * @see @see https://github.com/laminas/laminas-mail/issues/19
remove duplicate `@see`

2020-08-06 12:54 UTC, samsonasik commented on test/Transport/SendmailTest.php
> +     * @see @see https://github.com/laminas/laminas-mail/issues/19
fixed.

2020-08-06 12:54 UTC, samsonasik commented on test/Transport/SendmailTest.php
> +        $lineBreak = $this->isWindows() ? "\r\n" : "\n";
fixed.

2020-08-06 12:54 UTC, samsonasik commented on test/Transport/SendmailTest.php
> +    public function isWindows()
fixed.

2020-08-06 12:54 UTC, samsonasik commented on test/Transport/SendmailTest.php
> +        $this->assertNotRegExp('/^Subject: Greetings and Salutations\!$/m', $this->additional_headers);
fixed.

2020-08-06 14:07 UTC, weierophinney approved these changes

2020-08-06 14:09 UTC, merged