Fixes #17 : Fixes when set -f option, no set -f option automatically
laminas/laminas-mail pull request #104
Opened 2020-08-05 18:08 UTC by samsonasik

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

Re-create https://github.com/zendframework/zend-mail/pull/227 by @tzmfreedom Fixes #17 .  Original PR description : 

```
Zend\Mail\Transport\SendMail always append envelope-from parameter.
But I want to set any envelope-from.
In this PR, only when not set option -f, set -f option automatically.
This means if I set -ffoo@example.com or -bs -ffoo@example.com, Zend\Mail\Transport\Sendmail doesn't set -f option.
```

2020-08-05 19:45 UTC, weierophinney requested changes
I've made one suggestion to how you check for the `-f` flag.

Additionally, we need tests demonstrating that the `setParameters()` method uses the parameter passed to the transport and NOT the sender and/or from address when it is provided; currently, you only demonstrate it is used when provided, and not used when not present, but not the additional case where it is not provided and falls through to the sender or from address.

2020-08-05 19:45 UTC, weierophinney commented on src/Transport/Sendmail.php
> +        if (preg_match('/^\-f.+$/', $parameters) || strpos($parameters, ' -f') !== false) {
```suggestion
        if (strpos($parameters, '-f') !== false) {
```

This accomplishes the same thing, with one less operation.

2020-08-05 19:49 UTC, michalbundyra commented on src/Transport/Sendmail.php
> +        if (preg_match('/^\-f.+$/', $parameters) || strpos($parameters, ' -f') !== false) {
@weierophinney it doesn't seem right, imo

it's not the same, previously we accept `-f` at the beginning of when it is after a space.

I can imagine case `my-fancy-param` where `-f` is no at the beginning nor after a space.

2020-08-05 19:56 UTC, weierophinney commented on src/Transport/Sendmail.php
> +        if (preg_match('/^\-f.+$/', $parameters) || strpos($parameters, ' -f') !== false) {
Then do it as follows:

```php
if (preg_match('/(^| )\-f.+/', $parameters)) {
```

It doesn't make sense to have two conditions when it's essentially the same condition ("is there a -f switch provided?"). The above regex does the "at the beginning" as well as "following a space" conditions.

2020-08-05 20:00 UTC, michalbundyra commented on src/Transport/Sendmail.php
> +        if (preg_match('/^\-f.+$/', $parameters) || strpos($parameters, ' -f') !== false) {
that's better ;-) there is also redundant `\` before `-` in the regexp

2020-08-05 20:52 UTC, samsonasik commented on src/Transport/Sendmail.php
> +        if (preg_match('/^\-f.+$/', $parameters) || strpos($parameters, ' -f') !== false) {
@weierophinney updated.

2020-08-06 14:23 UTC, weierophinney approved these changes
I've combined the two unit tests into a single one backed by a data provider. I think it's ready to :ship: once tests have run.

2020-08-06 14:29 UTC, merged