Fix InvalidArgumentException for optional empty count for rfc2231 parameter wrapping
laminas/laminas-mail pull request #108
Opened 2020-08-19 09:55 UTC by glensc

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

https://tools.ietf.org/html/rfc2231 allows the sequence (internally $count) being missing:

```
        Content-Type: application/x-stuff;
         title*=us-ascii'en-us'This%20is%20%2A%2A%2Afun%2A%2A%2A
```

However `ContentDisposition` expected it to be number, and failed to cast empty string to numeric index. This resulted in throwing `InvalidArgumentException(code: 0): Invalid header line for Content-Disposition string - incomplete continuation`

Additionally, seems similar logic is needed ion ContentType class, but it's partly duplicated, ContentDisposition has more logic, and the exception is presented only in ContentDisposition class.

2020-08-20 08:57 UTC, glensc commented
WDYT of having @codingStandardsIgnoreStart equivalent enabled for all tests? or set the line lenght limit to 512 or something biggger than 120, that 120 quota is very easy to reach:

```
➔ grep -r @codingStandardsIgnoreStart test/|wc -l
19
```

2020-08-20 08:59 UTC, glensc commented
I don't know how to fight coverage, it says coverage increased, but still making status check failed

- https://coveralls.io/builds/32879718

> COVERAGE INCREASED (+0.09%) TO 62.259%

2020-08-21 08:13 UTC, glensc commented
@weierophinney how to indicate it's ready for merge from the developer? I removed draft status, but seems can't request a review as that probably requires being project member.

2020-08-21 08:47 UTC, froschdesign commented
@glensc 
> but seems can't request a review as that probably requires being project member.

Which is correct:

> **Note:** Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review

(But there is a bug here on GitHub so sometimes you can add a reviewer without special permissions.)

2020-08-21 08:56 UTC, samsonasik commented on test/Header/ContentDispositionTest.php
> +use Eventum\Mail\MailMessage;
it seems not used, can be removed.

2020-08-21 10:08 UTC, glensc commented
Updated, DCO & Travis pass.

2020-08-24 09:30 UTC, glensc commented
ping!

2020-08-31 10:55 UTC, glensc commented
another ping!

I'd like this to be in the next patch release. it's critical for us, and keeping production patched (hot fixed) is not very sustainable solution.

2020-09-17 13:32 UTC, glensc commented
@weierophinney @froschdesign @samsonasik ping

https://outlook.office.com/mail/inbox seems to create such mails, so it's pretty common and wild.

2020-09-18 07:06 UTC, glensc commented
and apparently Apple Mail as well: https://github.com/laminas/laminas-mail/pull/111

2020-10-04 19:28 UTC, glensc commented
@boesing seeing you active in this project (https://github.com/laminas/laminas-mail/issues/113), can you do something to get this PR (https://github.com/laminas/laminas-mail/pull/108) moving? waiting for the fix to be released for almost 50 days is depressive...

2020-10-04 21:04 UTC, boesing requested changes

2020-10-04 21:04 UTC, boesing commented on test/Header/ContentDispositionTest.php
> +            "Content-Disposition: attachment; filename*=utf-8''Capture%20d%E2%80%99e%CC%81cran%202020%2D05%2D13%20a%CC%80%2017.13.47.png",
If the line-length is too long (as stated in the travis build), just use string concatenation and split this line into two lines.

2020-10-04 21:15 UTC, boesing commented
@glensc I've created issues in every package today. ;-)

TBH, I am not that familiar with all that mail standards, e.g.
Furthermore, we voted to mark this package as security-only as (you can also see) we do not focus on this package anymore.

Laminas has a huge amount of packages (including all `mezzio` and `laminas-api-tools`) while we are just a bunch of people to maintain all these packages (most of us are volunteering tho). 

I'd like to have another one have a look on this and then we probably get to merge this. Thanks for your patience and sorry that it might take some time to get things merged (as we are focussing on other packages currently).

2020-10-04 21:19 UTC, boesing commented
From my perspective, this PR is fine. However, as I stated that I don't know much about all this stuff, I try to get someone to review this aswell.

2020-10-04 21:19 UTC, boesing approved these changes

2020-10-26 13:44 UTC, cedric-anne approved these changes
I had the same problem and applying this fix solves it.

2020-11-13 16:34 UTC, glensc commented
Can this be merged and released, please?

2020-12-31 11:37 UTC, Ocramius commented on test/Header/ContentDispositionTest.php
> +            "Content-Disposition: attachment; filename*=utf-8''Capture%20d%E2%80%99e%CC%81cran%202020%2D05%2D13%20a%CC%80%2017.13.47.png",
It's suppressed above: looks good as-is.

2020-12-31 11:38 UTC, Ocramius approved these changes
LGTM 🚢 

Sorry that it went under the radar 😱

2020-12-31 11:39 UTC, merged

2020-12-31 11:40 UTC, Ocramius commented
Thanks @glensc - going out for release right now

2020-12-31 11:41 UTC, glensc commented
It took a while, but at least still fixed in the same year :)

2021-03-21 11:52 UTC, glensc commented on src/Header/ContentDisposition.php
> +                            $type,
I think the `$type` is always `string|null` as `explode` and `list` can't return anything else.