Allow code to access the last response string.
laminas/laminas-mail pull request #110
Opened 2020-08-24 12:03 UTC by Piskvor

This does make the class stateful - OTOH that reflects the nature of an IMAP session.
- requestAndResponse() provides very rudimentary response for debugging negative responses
- it is at times useful to see the exact response of the server
- "NO [AUTHENTICATIONFAILED] Authentication failed." is far more informative than a FALSE
- also, there's currently no way to distinguish between different error states
- e.g. the above and "NO [INSUFFICIENTGROVEL] Zot!"

Signed-off-by: Jan Piskvor Martinec <github@piskvor.org>

|    Q          |   A
|-------------- | ------
| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

### Description

2020-08-24 16:41 UTC, glensc requested changes

2020-08-24 16:41 UTC, glensc commented on src/Protocol/Imap.php
> +    protected $lastResponseLine;
use private unless needed higher visibility?

2020-08-24 16:41 UTC, glensc commented on src/Protocol/Imap.php
> +        list($tag, $this->lastResponseLine) = explode(' ', $line, 2);
use short syntax:
`[$tag, $this->lastResponseLine] = explode(' ', $line, 2);`

2020-09-02 11:19 UTC, enumag commented on src/Protocol/Imap.php
> +
```suggestion
```

2021-05-20 04:04 UTC, closed without merging