Add PHP 8.0 support
laminas/laminas-mail pull request #117
Opened 2020-11-23 21:45 UTC by bfoosness

|    Q          |   A
|-------------- | ------
| New Feature   | yes

### Description

Close #114

2020-12-10 23:14 UTC, snapshotpl commented on .travis.yml
> +    - php: 'nightly'
`8.0` is supported now

2020-12-30 13:35 UTC, clementmas commented
Hey guys, what's the status on this PR? Can it be merged?

2020-12-30 13:52 UTC, bfoosness commented
> Hey guys, what's the status on this PR? Can it be merged?

This PR is blocked for the moment because there are still a few Laminas dependencies that haven't been updated to support PHP 8.0 yet.

2021-01-17 22:44 UTC, bfoosness commented
I think `laminas/laminas-crypt` is the only remaining dependency that needs to support PHP 8.

2021-01-17 22:47 UTC, bfoosness commented on test/Header/ContentDispositionTest.php
> +        yield 'With two ordered items ' => [
@glensc: This was introduced in https://github.com/laminas/laminas-mail/commit/44988d041c65876d68c56dc62294a096f19b98a8#, but it's conflicting with line 282:

```
1) Error
The data provider specified for LaminasTest\Mail\Header\ContentDispositionTest::testParameterWrapping is invalid.
PHPUnit\Framework\InvalidDataProviderException: The key "With two ordered items" has already been defined in the data provider "parameterWrappingProvider".
```

I wasn't sure what to call this, hence the extra space for now. What would you call this?

2021-01-18 10:20 UTC, glensc commented on test/Header/ContentDispositionTest.php
> +        yield 'With two ordered items ' => [
@bfoosness: submitted a fix: https://github.com/laminas/laminas-mail/pull/129

2021-01-20 14:59 UTC, bfoosness commented on test/Header/ContentDispositionTest.php
> +        yield 'With two ordered items ' => [
Thank you!

2021-01-26 13:09 UTC, bfoosness commented on test/Header/ContentDispositionTest.php
> +        yield 'With two ordered items ' => [
I rebased to include this fix.

2021-01-26 13:25 UTC, Ocramius requested changes
Just need to check if we can drop `--ignore-platform-reqs` before merging

2021-01-26 13:25 UTC, Ocramius commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
Is `--ignore-platform-reqs` still needed at this stage?

2021-01-26 13:25 UTC, Ocramius commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
Is `--ignore-platform-reqs` still needed at this stage?

2021-01-26 13:30 UTC, bfoosness commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
I believe laminas-crypt needs to be updated before we can do that? I also see I'm now including `- DEPS=lowest` where we previously only included `latest`, and I don't believe that's ever going to work because of an issue in laminas-stdlib 3.1. Let me remove those changes. It's still hard to tell what issues are outstanding since the Travis builds aren't running.

2021-01-26 13:33 UTC, Ocramius commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
Let's roll with the diff as-is for now then, and I'll create a follow-up ticket.

2021-01-26 13:35 UTC, Ocramius commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
https://github.com/laminas/laminas-mail/issues/131

2021-01-26 13:35 UTC, Ocramius commented on .travis.yml
> +        - COMPOSER_ARGS="--no-interaction --ignore-platform-reqs"
https://github.com/laminas/laminas-mail/issues/131

2021-01-26 13:35 UTC, Ocramius approved these changes
:ship:

2021-01-26 13:35 UTC, merged