Fold long lines following RFC 5322 section-2.2.3
laminas/laminas-mail pull request #140
Opened 2021-02-27 12:48 UTC by glensc

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description

It seems, the underlying problem of the bug is that currently, the loop reads up to 1000 bytes, and if the input is longer than that, then everything over 1000 bytes will appear as the next line in mail headers, resulting in corruption. And depending on MTA, such corruption is treated as the end of headers input or adds another mail header.

Updates https://github.com/laminas/laminas-mail/pull/138 by @vladsf with the solution described in https://github.com/laminas/laminas-mail/pull/138#issuecomment-787063554 and adds unit test.

2021-02-27 13:23 UTC, vladsf commented on src/Protocol/Smtp.php
> +        $chunkSize = 4906;
you mean 4096?

2021-02-27 13:27 UTC, vladsf commented on src/Protocol/Smtp.php
> +        if ($line) {
I guess this line requires escaping and folding too?

2021-02-27 13:36 UTC, vladsf commented on test/Transport/SmtpTest.php
> +     * @see https://github.com/laminas/laminas-mail/pull/138
pull/140 to be precise

2021-02-27 13:42 UTC, vladsf commented on src/Protocol/Smtp.php
> +        if ($line) {
I guess do { } while(fgets..); fits better in this case.

2021-02-27 13:55 UTC, vladsf commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
I don't understand this. One has read full chunk 4095, no line break found. Why to look for "\n" at 4094?

2021-02-27 16:29 UTC, glensc commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
That is for the scenario when the line is exactly of 4094 length, i.e not truncated.

For example, these both end up read of 4 bytes:
1. "123\n"
2. "1234"

but only the second example is "truncated", first one is exactly of the length of the buffer-1.

I tried to make testcase for this, but ended up finding another bug on Storage\Message not loading the wrapped headers back properly (injects ' ' at one (but not all!!!) wrap point).

2021-02-27 16:30 UTC, glensc commented on test/Transport/SmtpTest.php
> +     * @see https://github.com/laminas/laminas-mail/pull/138
Yeah, I did not plan to make new PR when I wrote the unit test :)

2021-02-27 16:32 UTC, glensc commented on src/Protocol/Smtp.php
> +        if ($line) {
Indeed, wrapping needed as well. Good catch! Yes, the code became quickly nasty.

I would add a new class dealing with reading and wrapping, but not sure if such refactoring would be accepted then. Some Generator that the original code can consume.

2021-02-27 16:32 UTC, glensc commented on src/Protocol/Smtp.php
> +        $chunkSize = 4906;
Absolutely correct! Nice catch!

2021-02-27 16:54 UTC, vladsf commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
fgets does not truncate "\n":
```
$ for i in {1..4094}; do echo -n '1' >>inputfile.txt; done
$ php fgets.php 
4094 49
$ >inputfile.txt
$ for i in {1..4093}; do echo -n '1' >>inputfile.txt; done
$ echo '' >>inputfile.txt
$ php fgets.php 
4094 10
```

```
<?php
$handle = @fopen("inputfile.txt", "r");
if ($handle) {
	while (($buffer = fgets($handle, 4096)) !== false) {
		echo strlen($buffer);
		echo " " . ord($buffer[strlen($buffer)-1]);
		echo "\n";
	}
```
so I'm sure `$buffer[$chunkSize - 2] !== "\n" `is correct.

2021-02-27 19:04 UTC, glensc commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
@vladsf, will check your input later, I wrote code based on `fgets` documentation. Did not test properly. Could be simple off by one issue here. 

I got distracted with `Storage\Message` bug, that result wasn't decoded properly.

2021-02-27 19:13 UTC, glensc commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
@vladsf indeed, the logic is inverted. if the line is incomplete the last char is not `\n`, otherwise, it is `\n`:

```php
#!/usr/bin/env php
<?php
$fname = "inputfile.txt";
file_put_contents($fname, str_repeat("A", 4096). "\n");

$handle = fopen($fname, "r") or die;

$chunkSize = 1024;
while (($buffer = fgets($handle, $chunkSize)) !== false) {
    $length = strlen($buffer);
    $c = $buffer[$length - 1];
    printf("len:%d of %d c=%s (ord:0x%x)\n", $length, $chunkSize, json_encode($c), ord($c));
}
```

```
len:1023 of 1024 c="A" (ord:0x41)
len:1023 of 1024 c="A" (ord:0x41)
len:1023 of 1024 c="A" (ord:0x41)
len:1023 of 1024 c="A" (ord:0x41)
len:5 of 1024 c="\n" (ord:0xa)
```

2021-02-27 22:05 UTC, glensc commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
> so I'm not sure $buffer[$chunkSize - 2] !== "\n" is correct.

it is correct. `fgets` reads maximum of `$chunkSize` bytes, if line is complete last byte is "\n". accessing last byte of `$buffer`, is at `strlen($buffer)-1` offset, so, if maximum read happens, then also `strlen($buffer) == $chunkSize-1`, so `strlen($buffer)-1` can be replaced with `$chunkSize-2`.

The condition could be replaced with:
```php
if (isset($buffer[$chunkSize - 2]) && $buffer[$chunkSize - 2] !== "\n") {
```

but not sure, maybe that's harder to read and understand?

2021-02-27 22:30 UTC, glensc commented on src/Protocol/Smtp.php
> +        if ($line) {
having `do {} while (fgets)`  gets awkward, as then need to check in the loop if $buffer is even initialized. so I'll use Generator, and do one yield after the loop than make the loop itself complicated.

See e80773f6 commit. I ended up reset `$line` to `null` to keep the support of sending empty lines (length=0).

2021-02-27 22:39 UTC, glensc commented
I would move `$chunkReader function` to a new class (preferred) or to this class method. But really need some guidance from The Maintainers.

2021-02-28 09:57 UTC, vladsf commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
It seems to me that is hard to read and triggers "array index out of bounds error" in my mind.
Could it be like this? -
`if (strlen($buffer) == $chunkSize-1) {
       if ($buffer[strlen($buffer) - 1] !== "\n") {`

2021-02-28 10:01 UTC, vladsf commented
I honestly believe that too much PHP force has been used :)

2021-02-28 10:06 UTC, vladsf commented
> I would move `$chunkReader function` to a new class (preferred) or to this class method. But really need some guidance from The Maintainers.

That was an impressive technique :)  Wouldn't be simpler to move "escaping, rtrim'ing and folding" a line into a function?

2021-02-28 10:32 UTC, glensc commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
the out of bounds access is protected with `isset`, and as the calculation is known ahead, there's optimization to avoid costly `strlen()` call in the loop.

there's a similar `isset($foo[0])` in the code, so it's not that mystical.

and in answer to you question, yes. the logic is the same. extra `if` with `strlen($buffer) == $chunkSize-1` is identical in behavior with `isset($buffer[$chunkSize - 2]) &&`

2021-02-28 10:38 UTC, glensc commented
> That was an impressive technique :) Wouldn't be simpler to move "escaping, rtrim'ing and folding" a line into a function?

what do you mean by "simpler", simpler to whom? to what? i offered to move the generator to class method, but not doing 'jus for that', as maybe maintainers accept it as is now.

also, I would be against putting three different logics to the same code block, it would make code more difficult to understand and follow the code flow. currently, it's distinct, reading and unfolding in one place, the rest in the other loop. the code gets smelly if they all done in the same loop (as you can see from commit history). need multiple state variables that are unrelated to each other but used in the same loop.

2021-02-28 11:14 UTC, vladsf commented on src/Protocol/Smtp.php
> +            if (strlen($buffer) === $chunkSize - 1 && $buffer[$chunkSize - 2] !== "\n") {
Yes, the logic is the same. I'm only sharing my readability concerns.

2021-02-28 11:16 UTC, vladsf commented
> what do you mean by "simpler", simpler to whom? to what? i offered to move the generator to class method, but not doing 'jus for that', as maybe maintainers accept it as is now.

For the maintainers to review the PR.

2021-02-28 12:00 UTC, glensc commented
> > what do you mean by "simpler", simpler to whom? to what? I offered to move the generator to class method, but not doing 'jus for that', as maybe maintainers accept it as is now.
> 
> For the maintainers to review the PR.

The aggregated diff is messy, but individual commit diffs are okay.

2021-02-28 16:32 UTC, glensc commented
Created reproducer of the bug I discovered that prevented of making more reasonable tests:
- https://github.com/laminas/laminas-mail/pull/142


Wanted to test like this:

```php
        $raw = substr($data, strpos($data, "DATA\r\n") + 6);

        $message = new StorageMessage(['raw' => $raw]);
        $headers = $message->getHeaders()->toArray();
        $this->assertEquals($bufferSizeHeaderValue, $headers['X-Exact-Length']);
        $this->assertEquals($headerValue, $headers['X-Ms-Exchange-Antispam-Messagedata']);
```

That's what I get when captured SMTP from this PR. It does look correct, so it's a bug in parsing of this library/

2021-03-05 07:11 UTC, glensc commented
Thought this could go with 2.13, but then saw that adapt to new CI flow would be missing, so changed back to 2.14.

2021-03-05 07:13 UTC, glensc commented
@Ocramius can you do the review, merge, and release dance? thank you!

2021-03-05 07:33 UTC, Slamdunk requested changes

2021-03-05 07:33 UTC, Slamdunk commented on test/Transport/SmtpTest.php
> +        foreach ($lines as $line) {
In the way the test is written, somehow someday `$data` could turn empty, and the assertions inside `foreach` go silently ignored. Please add an assertion to verify there's a content, the more precise the better:

```suggestion
        $this->assertCount(123, $lines);
        foreach ($lines as $line) {
```

2021-03-05 07:44 UTC, glensc commented
@vladsf I've changed the chunk_split argument to 997, as leading space on the "new" line, also adds a byte:

- Input: `"1234567890123456\n"`
- Split: `"123456789\r\n 0123456\n"`
  - Line1; `"123456789\r\n`
  - Line2: `" 0123456\n"` (note the leading space)

This came up after I fixed the test not to accept anything over 998.

2021-03-05 07:46 UTC, glensc commented on test/Transport/SmtpTest.php
> +        foreach ($lines as $line) {
@Slamdunk good catch! Committed.

2021-03-05 07:56 UTC, Slamdunk requested changes

2021-03-05 07:56 UTC, Slamdunk commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
The code looks good, but I'm puzzled by all these hardcoded numbers: 1000, 998, 997, 2, both in the tests and in the src.
Your comments to the code are greats, but I fear that if someone will ever change one of these, another one get forgotten.

Could you try to refactor all of them into verbose `Protocol\Smtp` constants and combinations of them?

2021-03-05 09:10 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
Well, that's for the unit tests exist, right?

In overall:
- the line length must be at most 1000 bytes
- the line must be terminated with `\r\n`, so it's 998
- now the 997 for chunker, comes from the fact that `Headers::FOLDING` inserts space at the new line, see this comment: https://github.com/laminas/laminas-mail/pull/140#issuecomment-791226698

I can add constant 1000, and use -2 and -1, but these rely on what exactly is contained in Headers::FOLDING constant. so if someone changes that constant the calculations would be off again.

and making the logic super smart by inspecting what is in Headers::FOLDING seems counterproductive as the constant will never be changed, and if it's changed there are tons of places that can go wrong.

so I'm, contradicted what constants to add, as adding 3 constants seems odd as well.

2021-03-05 09:29 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
Added MAX_LINE_LENGTH constant. Please mark discussion resolved if this is an acceptable outcome.

2021-03-05 09:53 UTC, Slamdunk commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
I would be perfectly fine having `strlen(Headers::FOLDING)` everywhere, because this code is tricky, and readability should come first.
I would also like a `const SPACE_LENGTH = 1`: the more readable the code is, the easier it is to understand

2021-03-05 09:59 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
@glensc @Slamdunk Please consider renaming MAX_LINE_LENGTH to SMTP_LINE_LIMIT. This is not a library limit but SMTP protocol limit.

2021-03-05 10:01 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
@glensc Changing to 997 is correct! Good fix!

2021-03-05 10:07 UTC, Slamdunk commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> Please consider renaming MAX_LINE_LENGTH to SMTP_LINE_LIMIT. This is not a library's but SMTP protocol limit.

:+1:

2021-03-05 10:18 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
@Slamdunk `strlen(Headers::FOLDING)` is incorrect and source of new bugs. it depends that the folding has one space after "\r\n". SPACE_LENGTH seems also a pointless constant that's been used only once.

also, the strlen is not needed, as the RFC explicitly says 998 must be used.

I rather add a test that tests that `Headers::FOLDING` has exactly the current value.

2021-03-05 10:21 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> @glensc @Slamdunk Please consider renaming MAX_LINE_LENGTH to SMTP_LINE_LIMIT. This is not a library's but SMTP protocol limit.

Not convinced that's necessary, the constant is in class Protocol\SMTP, so it's already in code specific to SMTP protocol... and it's accompanied with a comment and with a link to specification.

2021-03-05 10:29 UTC, Slamdunk commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> @Slamdunk `strlen(Headers::FOLDING)` is incorrect and source of new bugs. it depends that the folding has one space after `"\r\n"`. `SPACE_LENGTH` seems also a pointless constant that's been used only once.
> 
> also, the strlen is not needed, as the RFC explicitly says 998 must be used.

Ok



> I rather add a test that tests that `Headers::FOLDING` has exactly the current value.

That would help



> Not convinced that's necessary, the constant is in class Protocol\SMTP, so it's already in code specific to SMTP protocol... and it's accompanied with a comment and with a link to specification.

Ok


Still it's hard to me to understand what the `2` here stands for:

https://github.com/laminas/laminas-mail/pull/140/files#diff-1aa66d5ccd570f8fab05c2a05fe3b18ae45d4866faf5e83dcd64993a04d0ba2aR205

Why `2` and not `1`? Please reply not here but in the code

2021-03-05 10:50 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> Not convinced that's necessary, the constant is in class Protocol\SMTP, so it's already in code specific to SMTP protocol... and it's accompanied with a comment and with a link to specification.

Well, I am missing the purpose code review then if there is only one way to go. People read code many times, why not to help them to avoid readins comment?? SMTP_LINE_LIMIT clearly states it is can not be increased while MAX_LINE_LENGTH might be. 

e.g. I do think the patch needs to be some complex. RFC only states the line must be 998 characters long at max, but it does not state _where_ longs line have to broken. E.g. I don't think the library has to read an endless line until "\n" is met or PHP runs out of memory. There is no much reason to read a 1MB line and then split it. _Default_ 8K is good enough.

2021-03-05 11:52 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> Well, I am missing the purpose of code review then if there is only one way to go. 

I disagreed with the constant need to include SMTP in it, with a counterargument, the other reviewer accepted that. The code review can go endlessly if every now someone throws something in, conflicting with previous review notes.

> People read code many times, why not to help them to avoid reading comments?? SMTP_LINE_LIMIT clearly states it can not be increased while MAX_LINE_LENGTH might be.

apparently, you did not explain yourself clearly initially, seemed to me you argued about protocol SMTP not being in the constant name, but now seems you mean about MAX vs LIMIT. now I see the difference.

Also, Why do I write code comments if nobody reads them?

> More on this topic, I do not think the patch needs to be so complex. 

In my opinion, the current code with the generator is simplex rather than complex, the reader deals with reading in chunks emitting full lines. reader consumer always gets a full line.

> RFC only states the line must be 998 characters long at max, but it does not state where longs lines have to broken. E.g. I don't think the library has to read an endless line until "\n" is met or PHP runs out of memory. There is no much reason to read a 1MB line and then split it. Default 8K is good enough.

I strongly disagree with statements like "Some value is good enough", as that's what got this into first place, someone thought earlier 1000 is good enough, but that resulted in longer lines than 1000 a data corruption, so your idea just to up limit will do exactly that, for someone sending 9K line will cause a corruption:
- https://github.com/laminas/laminas-mail/pull/138#issuecomment-787063554

your solution did not deal with the problem that if a line is partially read (longer than buffer size), a proper folding is added.

2021-03-05 12:00 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> Why 2 and not 1? Please reply not here but in the code

it's combining -1 to access last char, and -1 because how how `fgets()` work:
> `fgets()`: Returns a string of up to `length-1` bytes read from the file pointed to by handle. If there is no more data to read in the file pointer, then false is returned.

- https://www.php.net/fgets


see the previous discussion:
- https://github.com/laminas/laminas-mail/pull/140#discussion_r584196792

can you help, how to explain it in the code?

adding intermediate variables could help, but it's not good practice to do such things in a loop just for readability...

do you feel better if the code calls `fgets(...$buffsize+1)`, so the check would be `$bufsiz-1`?

2021-03-05 12:13 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
here's something i've came up with:

```php
while (($buffer = fgets($handle, $chunkSize)) !== false) {


    // This is optimization to avoid calling length() in a loop.
    // We need to match a condition that is when:
    // 1. maximum was read from fgets, which is $chunkSize-1
    // 2. last byte of the buffer is not \n
    //
    // when maximum is read, the last byte of buffer is at $chunkSize-2:
    // - strlen($buffer) === $chunkSize-1
    // - strlen($buffer)-1 === $chunkSize-2
    // - $buffer[strlen($buffer) - 1] === $buffer[$chunkSize-2]
    if (isset($buffer[$chunkSize - 2]) && $buffer[$chunkSize - 2] !== "\n") {
        printf("x1: -> line is truncated\n");
    }
```

cold also do this, but this is against doing "useless" things in a loop:

```php
    $lastByte = $buffer[$chunkSize - 2] ?? null;
    if ($lastByte !== "\n") {
        printf("x1: -> line is truncated\n");
    }
```

2021-03-05 12:43 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> I strongly disagree with statements like "Some value is good enough", as that's what got this into first place, someone thought earlier 1000 is good enough, but that resulted in longer lines than 1000 a data corruption, so your idea just to up limit will do exactly that, for someone sending 9K line will cause a corruption:
> 
>     * [#138 (comment)](https://github.com/laminas/laminas-mail/pull/138#issuecomment-787063554)
> 
> 
> your solution did not deal with the problem that if a line is partially read (longer than buffer size), a proper folding is added.

Closed PR #140 proposes a correct folding. That comment was a temporary workaround.

I guess PHP_SOCK_CHUNK_SIZE was set 8K for a purpose (unknown to be though). May be for for quicker read-send-read-send operations. SMTP communication does not requires all broken lines to of equal size. It can accept and "unfold" lines of any size later. This example folded lines are equal once "unfolded":
```
<SPACE>ABCDEF
<SPACE>ABCDEF
```
```
<SPACE>AB
<SPACE>CDEF
<SPACE>ABCD
<SPACE>EFABCDEF
```
So I am trying to explain that sending folded 8K string is good enough and there is little win in reading e.g. 800K line and then fold'ing it once and only one has been full.

2021-03-05 12:48 UTC, Slamdunk approved these changes

2021-03-05 13:09 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
the lines I suggested looks more readable to me. One checks the buffer size and tests the last byte. 
```
if (strlen($buffer) == $chunkSize-1) { 
       if ($buffer[strlen($buffer) - 1] !== "\n") {
..
```

2021-03-05 13:10 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
readability is more important than strlen/isset speed difference.

2021-03-05 13:42 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> So I am trying to explain that sending folded 8K string is good enough and there is little win in reading e.g. 800K line and then fold'ing it only one has been fully read.

and I'm saying "good enough" is not a fix, but a workaround. your code does not distinguish between a truncated and complete line.

2021-03-05 13:44 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> the lines I suggested looks more readable to me. One checks the buffer size and tests the last byte.
> readability is more important than strlen/isset speed difference.

There's no need to repeat same text over and over! I replied then and I reply now, not going o change if maintainers do not request such change, and so far they have not given their opinion on the matter. and to you it may be readable, to me, it's even harder to read.

2021-03-05 14:14 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> and I'm saying "good enough" is not a fix, but a workaround. your code does not distinguish between a truncated and complete line.

There is no reason to read full line which exceeds 8K chracters. It only adds a vulnerability.

2021-03-05 14:16 UTC, vladsf commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
> can you help, how to explain it in the code?

You asked so I answered.

2021-03-05 16:08 UTC, glensc commented on test/Transport/SmtpTest.php
> +        $bufferSizeHeaderValue = substr($buffer, 0, 998 - strlen('X-Exact-Length') - 2);
>> can you help, how to explain it in the code?
>
> You asked so I answered.

No, [that][1] was reply to @Slamdunk [question][2]

[2]: https://github.com/laminas/laminas-mail/pull/140#discussion_r588191660
[1]: https://github.com/laminas/laminas-mail/pull/140#discussion_r588243003

2021-03-05 16:43 UTC, vladsf commented on src/Protocol/Smtp.php
> +            $lastByte = $buffer[$chunkSize - 2] ?? null;
Sorry, lastByte means the last byte and it can't be Null. The name of the variable contradicts its value.

2021-03-05 19:34 UTC, vladsf commented on src/Protocol/Smtp.php
> +            }
Why to reinvent reading a line if `fgets($fp)` will keep reading from the stream until it reaches the end of the line?
Just as simple as -
```
while (($buffer = fgets($fp)) !== false) {
  yield $buffer;
}
```

2021-03-05 20:40 UTC, glensc commented on src/Protocol/Smtp.php
> +            }
@vladsf I've explained this to you multiple times, and I'm tired already, and for the last time: that's the underlying problem, such code can't distinguish between whole line and partial line, resulting in corruption that this PR is fixing.

run the code if you don't understand the explanations and don't understand how fgets works and why the switch was made to fgets (I've explained it!).

2021-03-05 20:42 UTC, glensc commented on src/Protocol/Smtp.php
> +            $lastByte = $buffer[$chunkSize - 2] ?? null;
I don't see you suggesting a better name. What's the point of such reviews?

- https://www.mediawiki.org/wiki/Naming_things

2021-03-05 20:52 UTC, vladsf commented on src/Protocol/Smtp.php
> +            }
Surely I forgot this _read-the-full-line_ nuance because you removed my comment from initial commit which had this explained this `// read the line up to PHP_SOCK_CHUNK_SIZE` and it's only a week passed. Imagine another contributor looking into the code and having no clue why reading using $chunkSize and why the $lastByte is always null if $chunkSize > PHP_SOCK_CHUNK_SIZE.

2021-03-05 20:55 UTC, vladsf commented on src/Protocol/Smtp.php
> +            $lastByte = $buffer[$chunkSize - 2] ?? null;
I need a break for ideas.

2021-03-05 21:14 UTC, glensc commented on src/Protocol/Smtp.php
> +            }
`// read the line up to PHP_SOCK_CHUNK_SIZE` comment is removed because it's bogus to keep, the current code does behave that way. I've explained it in the notes in the PRs before making the change, and after I've made the change. I'm tired of explaining the same thing over and over to you, which you just discard.

2021-03-05 21:17 UTC, glensc commented on src/Protocol/Smtp.php
> +            }
> *snip* if $chunkSize > PHP_SOCK_CHUNK_SIZE.

`PHP_SOCK_CHUNK_SIZE` is irrelevant in any way, comment on the current code, not the past code. see the commits, see the diffs.

2021-03-06 11:28 UTC, vladsf commented on src/Protocol/Smtp.php
> +            $lastByte = $buffer[$chunkSize - 2] ?? null;
@glensc, @Slamdunk  I suggest following readability improvement which speaks for itself without comments:
```
$lineBreak = $buffer[-1] ?? null;
if ($lineBreak === "\n") {
  yield $line;
  $line = null;
}
```

2021-03-06 14:36 UTC, vladsf commented on src/Protocol/Smtp.php
> +    private static function chunkedReader(string $data, int $chunkSize = 4096): Generator
Test method is named `testLongLinesFoldingRFC5322`. @glensc @Slamdunk I suggest renaming `chunkedReader` it to `longLineReader` so it conforms with the test method name and its primary purpose - to read long lines complete. It does not return chunks, it returns lines.

2021-03-15 10:16 UTC, glensc commented
@Slamdunk made a fresh rebase against `upstream/2.14.x`, perhaps it's easier to review knowing it's up to date with the base branch.

2021-03-17 12:41 UTC, Slamdunk commented
Thank you @glensc, I'm going to squash this PR to reduce `git-blame` and `git-bisect` verbosity

2021-03-17 12:41 UTC, merged

2021-03-17 15:24 UTC, glensc commented
@Slamdunk perhaps you should have asked first from authors for permission to squash!

This PR has waited for two weeks+ being idle! If this was an issue, should have said it in that time period!

I (try to) follow the atomic commits principle:
- https://www.freshconsulting.com/atomic-commits/

As I see it, you made the opposite: more difficult to git blame/bisect with squashing. And losing commit author information is not very friendly either.

2021-03-17 15:25 UTC, glensc commented
Update: seems this got merged without squashing, at least the 542686ae merge commit. So far so good.

2021-03-17 15:25 UTC, glensc commented
@Slamdunk thank you for the 2.14.0 release!

2021-03-17 15:27 UTC, glensc commented
Seems the release automation can't handle that PR had multiple contributors:
- https://github.com/laminas/laminas-mail/releases/tag/2.14.0

> 140: [2.14]: Fix: Fold long lines during SMTP communication thanks to @glensc

it actually replaced #138 by @vladsf yet there's no credit about that.