fix has timed out
laminas/laminas-mail pull request #167
Opened 2021-09-21 11:24 UTC by kokspflanze

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | yes
| QA            | yes

### Description

If there is no timeout it goes into the RuntimeException, so its not possible to send mails.

2021-09-21 11:31 UTC, Ocramius requested changes

2021-09-21 11:31 UTC, Ocramius commented on src/Protocol/AbstractProtocol.php
> -        if (! $info['timed_out']) {
Is there a meaningful way to verify this / avoid further regressions?

2021-09-21 11:41 UTC, kokspflanze commented on src/Protocol/AbstractProtocol.php
> -        if (! $info['timed_out']) {
Before the last release 2.14.2 it was `if (! empty($info['timed_out'])) {`.

I can also change it back to the old way.
Both ways would work fine for me.

2021-09-21 11:48 UTC, Ocramius commented on src/Protocol/AbstractProtocol.php
> -        if (! $info['timed_out']) {
I suppose `$info['timed_out']` can also be absent.

My question is whether there's a test case for this.

2021-09-21 11:57 UTC, kokspflanze commented on src/Protocol/AbstractProtocol.php
> -        if (! $info['timed_out']) {
from docs it looks like, its everytime there.
i also have no test case with a timed_out connection.

My case was only that all connections goes into that error, so no mailing was possible. (starting with 2.14.2).
For me looks like a simple true/false misstake.

So i created a fast easy PR, to help other ppl not waste again 1h to search that error.

2021-09-21 12:02 UTC, Ocramius commented on src/Protocol/AbstractProtocol.php
> -        if (! $info['timed_out']) {
> For me looks like a simple true/false misstake.

Yes, but while I understand the fix, we want tests to prevent this from happening again.

The question is: is this testable? Can we do it, to prevent the error from re-appearing in future changes/refactoring?

 > So i created a fast easy PR, to help other ppl not waste again 1h to search that error.

That's exactly what a test does :)

2021-09-22 16:11 UTC, alexeyamitech commented
This is affecting magento 2 module "mageplaza/magento-2-smtp"
The error message logged "smtp.gmail.com has timed out", which makes you think something is wrong with a server connectivity.

2021-09-22 19:03 UTC, lcobucci commented on src/Protocol/AbstractProtocol.php
> -        if (! $info['timed_out']) {
I didn't checkout the code but something like this **could** work (many warnings here because opening a connection with a random service and because the implementation is naive):

```php
/** @test */
public function exceptionShouldBeRaisedWhenConnectionHasTimedOut(): void
{
    $protocol = new class('httpstat.us', 80) extends AbstractProtocol {
        use ProtocolTrait;

        public function connect(): void
        {
            $this->socket = $this->setupSocket('tcp', $this->host, $this->port, 2);
        }

        public function send(string $path, int $readTimeout): string
        {
            $this->_send('GET ' . $path . ' HTTP/1.1');
            $this->_send('Host: ' . $this->host);
            $this->_send('');

            return $this->_read($readTimeout);
        }
    };
    
    $protocol->connect();
    self::assertSame('HTTP/1.1 200 OK' . AbstractProtocol::EOL, $protocol->send('/200?sleep=2000'));

    $this->expectExceptionObject(new Laminas\Mail\Protocol\Exception\RuntimeException('httpstat.us has timed out'));
    $protocol->send('/200?sleep=2000', 1);
}
```

Maybe custom stream wrappers can help us to isolate things but it might be a bit trickier...

2021-09-23 07:00 UTC, Ocramius commented
@Slamdunk I suggest running a `composer update` after setting `config.platform.php=7.3.99` or such: then this could work 👍

2021-09-23 07:06 UTC, Slamdunk commented
I'm fixing CS/SA, but PHP 7.3 kicks on Githug Actions:
```
Symfony\Component\Process\Exception\ProcessTimedOutException: The process "'/usr/bin/php7.3' '-S' '127.0.0.1:8080' '-t' '/github/workspace/test/Protocol/HttpStatusService'" exceeded the timeout of 60 seconds.
```
May we ignore this error, or better, raise minimum PHP version?

2021-09-23 07:08 UTC, Ocramius commented
> raise minimum PHP version?

For a patch release we cannot, but we can skip the test on lower versions, and bump the dependencies on 2.15

2021-09-23 07:16 UTC, Slamdunk commented on src/Protocol/AbstractProtocol.php
> -        if (! $info['timed_out']) {
Thank you @lcobucci for this proto; I've made `httpstat.us` service local and the test is perfect.

This is what OSS should be: someone with good ideas, someone with time and will to implement them, everyone involved.

We need a new licence: get paid to collaborate, free to use, pay to complain

2021-09-23 07:17 UTC, merged

2021-09-23 08:47 UTC, perfpcs commented
Hello, So will all these changes also be added to M 2.4.3  with release of 2.15.x or next version?  I am just wondering how it will update to the newer files. Sure I could add manually but figure I'd ask here what the plan is for release to all?
thanks

2021-09-23 08:56 UTC, froschdesign commented
@perfpcs 
The releases are already there:

* https://github.com/laminas/laminas-mail/releases/tag/2.14.3
* https://github.com/laminas/laminas-mail/releases/tag/2.15.1

And both contain the bug fix.

2021-09-23 08:58 UTC, Ocramius commented
Thanks @Slamdunk! :+1:

2021-09-23 09:04 UTC, perfpcs commented
Awesome thank you @froschdesign  and @Slamdunk . You guys got on this fast!

2021-09-23 09:07 UTC, froschdesign commented
Thanks goes to @Slamdunk @lcobucci and @Ocramius!