Define required intl extension constants
laminas/laminas-mail pull request #176
Opened 2021-11-05 01:05 UTC by ghostwriter

|    Q          |   A
|-------------- | ------
| Bugfix        | yes

### Description

- Add failing test 
- Remove ext-intl extension for testing 
- Define missing intl extension constants
- Resolves #175

2021-11-05 04:02 UTC, glensc commented on .laminas-ci/pre-run.sh
> +echo "Removeing $INTL_EXTENSION extension:"
```suggestion
echo "Removing $INTL_EXTENSION extension:"
```

2021-11-05 04:02 UTC, glensc commented on .laminas-ci/pre-run.sh
> +/usr/local/bin/php-extensions-with-version.php
missing EOL

2021-11-05 04:04 UTC, glensc commented on src/Header/AbstractAddressList.php
> +    define('IDNA_DEFAULT', 0);
i'm sure this is not okay test, what if the `symfony/polyfill-intl-idn polyfill` is loaded (or any other), in that case the `extension_loaded('intl')` is `false`, but the constants are defined.

you should check each constant on it's own for such cases

2021-11-05 04:09 UTC, glensc commented on src/Header/AbstractAddressList.php
> +    define('IDNA_DEFAULT', 0);
also, perhaps this is not the way you should recover this. the errors came because the constants are being defined as class constant `self::IDNA_ERROR_MAP`:
- https://github.com/laminas/laminas-mail/blob/2.15.1/src/Header/AbstractAddressList.php#L18-L32

but move these to some function, `getIdnaErrorMap()`, so they would be referenced only if using ext-intl mode, which means you don't need to affect PHP runtime global state by defining constants

2021-11-05 04:10 UTC, glensc commented on test/HeadersTest.php
> +    /** @group issues-175 */
```suggestion
    /** @group issue-175 */
```

makes more sense to use singular than plural

2021-11-05 04:19 UTC, glensc commented on src/Header/AbstractAddressList.php
> +    define('IDNA_DEFAULT', 0);
Maybe an even better refactor would be to extract the idn/intl stuff to own class, out of `AbstractAddressList`, due to S of SOLID principle, IdnaConverter->idnToAscii perhaps?
- https://www.digitalocean.com/community/conceptual_articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design

ps, there's another idn related library:
- https://github.com/algo26-matthias/idna-convert

2021-11-05 04:41 UTC, ghostwriter commented on src/Header/AbstractAddressList.php
> +    define('IDNA_DEFAULT', 0);
Thanks for the feedback, I'll revisit this section tomorrow.

2021-11-05 04:46 UTC, ghostwriter commented on src/Header/AbstractAddressList.php
> +    define('IDNA_DEFAULT', 0);
thoughts on requiring [`symfony/polyfill-intl-idn`](https://github.com/symfony/polyfill-intl-idn) via composer instead?

2021-11-05 06:57 UTC, glensc commented on src/Header/AbstractAddressList.php
> +    define('IDNA_DEFAULT', 0);
but, look, the other idn library is already in the required library list:
- https://github.com/laminas/laminas-mail/blob/2.15.1/composer.json#L18

why you getting intl errors is because of bad implementation (using constants of library that's not used), that's the root of the problem.

2021-11-30 14:39 UTC, Slamdunk requested changes
Overall looks good to me.

Please try to raise the minimum version of deps to see if build passes, and check out the few errors in both static analysis and coding standard :muscle:

2021-11-30 14:39 UTC, Slamdunk commented on src/Header/AbstractAddressList.php
> +            self::$punycode = new ToIdn();
DocBlock type for `self::$punycode` must be updated as well.

2022-01-17 08:50 UTC, Slamdunk approved these changes

2022-01-17 08:50 UTC, Slamdunk commented
Thank you @ghostwriter

2022-01-17 08:51 UTC, merged