trim surrounding single quotes in emails
laminas/laminas-mail pull request #183
Opened 2022-02-22 17:29 UTC by CapnFelix

Outlook does add single quotes to emails sometimes which is not valid

|    Q          |   A
|-------------- | ------
| Documentation |no
| Bugfix        | yes
| BC Break      |no
| New Feature   |no
| RFC           | no
| QA            | no

### Description

We're seeing emails generated by outlook which do have surrounding single quote like this:
`To: <'user@example.com'>`
The fix does just trim those.
 
This is my first PR, so please let me know if did something wrong :)

2022-02-22 18:53 UTC, Ocramius requested changes
Tests strictly required to validate such a change: IMO not valid to accept a string within quotes as a valid `Address` anyway, as such kind of cleanup should occur wherever you input data into the system that uses `Address::fromString()`

2022-02-22 18:53 UTC, Ocramius commented on src/Address.php
> +        $email = trim($email, '\'');
This should already fail validation above, no?

2022-02-23 09:42 UTC, CapnFelix commented on src/Address.php
> +        $email = trim($email, '\'');
Hm, no... the exception is actually thrown in the __contsruct():

```
Laminas\Mail\Exception\InvalidArgumentException: ‘example.com'' is not a valid hostname for the email address in /var/www/html/projectname/vendor/laminas/laminas-mail/src/Address.php:72
Stack trace:
#0 /var/www/html/projectname/vendor/laminas/laminas-mail/src/Address.php(48): Laminas\Mail\Address->__construct(‘’email…’, NULL, '')
#1 /var/www/html/projectname/vendor/laminas/laminas-mail/src/Header/AbstractAddressList.php(99): Laminas\Mail\Address::fromString('__construct(Array)
#11 /var/www/html/projectname/vendor/laminas/laminas-mail/src/Storage/AbstractStorage.php(270): Laminas\Mail\Storage\Imap->getMessage(3)
#12 /var/www/html/projectname/code/MyLaminasImapClient.php(137): Laminas\Mail\Storage\AbstractStorage->current() 
…
```

2022-02-23 09:59 UTC, CapnFelix commented
Thanks for the quick feedback.
I agree that stripping it in ::fromString is not perfect, even though when looking at the caller stack, I'm not quite sure where to put this instead.

Message is loaded from IMAP in
`Laminas\Mail\Storage\Imap->getMessage()`
which is then calling `\Laminas\Mail\Storage\Message`
and then finally using `\Laminas\Mail\Header\AbstractAddressList::fromString` to generate the AddressList.
I think it would be possible to do the trimming here, but I would need to use the same reg ex to unpack the email address.
What do you think?

2022-02-23 10:02 UTC, Ocramius commented
Aha, the fact that it is loaded via IMAP is new info.

I wonder if it is possible to get one of the loaded raw messages as part of data provider entries for our test suite? That would make it clear that we're talking about a real-world IMAP use-case, and prevent future regressions.

2022-02-23 11:17 UTC, CapnFelix commented
I am sorry, I should have provided this info in the initial description.
I've added a regression test to verify the change + added an example mail to the files folder.
Does this make sense?

2022-02-23 11:19 UTC, Ocramius commented on test/_files/mail_surrounding_single_quotes.eml
> +To: <'foo@example.com'>
We should probably use this mail in our tests somewhere :D

2022-02-23 11:42 UTC, CapnFelix commented on test/_files/mail_surrounding_single_quotes.eml
> +To: <'foo@example.com'>
makes sense... :D 
haven't found the place so far, will look into that later...

2022-02-23 12:09 UTC, Ocramius requested changes
Tests make sense to me, although the type errors reported by psalm should really be checked (see them on the diff).

As for the `trim()` call, I'm thinking that it should be moved into `Message`, rather than in `Address`. Rationale: `Address::fromString()` is used outside the context of `Message` too, while it looks like this Outlook IMAP oddity is only applicable when parsing messages in Outlook.

2022-02-23 13:02 UTC, CapnFelix commented
Maybe there is a small misunderstanding: We're looking at a message sent from an outlook client to a Gmail inbox. We're actually downloading this message via IMAP from Gmail in this case. 
So I guess this is more a general problem not related to the storage since it is the email that is "wrong" no matter which protocol I'm using to download it.
But I can look into a way to do that fix in `Message`...

2022-02-23 13:34 UTC, CapnFelix commented
Some thoughts looking at it a little more in depths:
what the `Address::Address::fromString` really does is extracting name and email from an address header value string. So I think it would make sense to enhance the extracting to be able to deal with the single quotes either by adjusting the preg_match or by doing the trimming.
When looking at the `Message` class I don't really have a good idea how to fix it there.
Let me know what you think! 
Thanks!

2022-02-23 14:24 UTC, Ocramius commented
Reasoning seems fine: are you able to bring CI to green, so that somebody else can throw in a more informed review on whether putting this responsibility in `Address` is acceptable?

2022-02-23 14:49 UTC, Slamdunk commented
> Issue on microsoft.com: https://answers.microsoft.com/en-us/outlook_com/forum/all/single-quote-marks-around-email-addresses-in/37122680-0ea2-46ed-bfeb-8f67d3441e5f

I've read https://datatracker.ietf.org/doc/html/rfc5322 twice, and nowhere it allows `<'foo@example.com'>` as valid syntax :facepalm: 

But as maintainer of [ddeboer/imap](https://github.com/ddeboer/imap) it's no surprise to me

2022-02-23 14:50 UTC, Slamdunk approved these changes

2022-02-23 14:56 UTC, Ocramius commented
Ok, so let's get it green, then merged

2022-02-23 15:00 UTC, CapnFelix commented
Awesome! 
I am not familiar with psalm yet, but I think I got it to work :D

2022-02-23 21:08 UTC, Ocramius approved these changes
Awesome! :ship: 

Thanks @CapnFelix! Releasing nao.

2022-02-23 21:08 UTC, merged

2022-02-24 13:40 UTC, CapnFelix commented
Thank you so much! 🌊