Add support for Microsoft POP3 XOAUTH2
laminas/laminas-mail pull request #200
Opened 2022-07-29 07:51 UTC by griesi007

Signed-off-by: griesi007 <noreply@12live.de>

Add support for Microsoft POP3 via modern authentication in addition to rejected pull request #199 with required integration tests

$storage = new \Laminas\Mail\Storage\Pop3(
	Laminas\Mail\Protocol\Pop3\Xoauth2\MicrosoftFactory::getInstance(
		'Outlook.office365.com',
		'mail@example.com',
		'xoauth2SaslEncodedClientResponse'
	)
);

2022-08-10 13:41 UTC, Slamdunk requested changes
Thank you @griesi007 for the improvements over the first PR.
Check the few changes I pinpointed and let's see how the shape looks.
Please rebase the PR as the first step.

2022-08-10 13:41 UTC, Slamdunk commented on src/Protocol/Pop3/Xoauth2/Microsoft.php
> +    public function authenticate(string $xoauth2Sasl): void
Instead of adding a new API, I think we can reuse the `login` method.

2022-08-10 13:41 UTC, Slamdunk commented on src/Protocol/Pop3/Xoauth2/MicrosoftFactory.php
> +class MicrosoftFactory
I don't think we need a factory for this.

The user could will look like:

```php
$protocol = new Xoauth2\Microsoft("host", "port", "ssl");
$protocol->login("user", "token");

$storage = new Pop3($protocol);
```

Users can do that by their own.

2022-08-10 13:41 UTC, Slamdunk commented on src/Protocol/Xoauth2/Xoauth2.php
> +class Xoauth2
We are going to need this functionality in multiple part for sure, but we can make it `final` and `@internal`

2022-08-10 13:41 UTC, Slamdunk commented on src/Protocol/Pop3/Xoauth2/Microsoft.php
> +class Microsoft extends \Laminas\Mail\Protocol\Pop3
I see you didn't make it `final` because it needs to be tested with a subclass.
I'm ok with it (our fault architecture doesn't allow a better mocking experience) but still we can add a `@final` docblock, so inheritance in user code gets disabled.

2022-08-10 13:41 UTC, Slamdunk commented on test/Protocol/Pop3/Xoauth2/MicrosoftTest.php
> +            public function __construct()
This can be removed

2022-08-10 13:41 UTC, Slamdunk commented on test/Protocol/Pop3/Xoauth2/MicrosoftTest.php
> +        $this->assertInstanceOf(Microsoft::class, $protocol);
I'd like to see an assertion on the `socket`, that is has received the `AUTH XOAUTH2` string

2022-08-10 14:16 UTC, griesi007 commented on src/Protocol/Pop3/Xoauth2/Microsoft.php
> +    public function authenticate(string $xoauth2Sasl): void
@Slamdunk yes we might. What I do not like with this idea are that we are forced to use the misleading parameters named username / password and the 3rd parameter which doesn´t have any effect at all when we opt-in for overwritung the login method. Basically it depends if you want to make the code as explicit as possible or as easy as possible to use. I would prefer the first approach.

2022-08-10 14:28 UTC, Slamdunk commented on src/Protocol/Pop3/Xoauth2/Microsoft.php
> +    public function authenticate(string $xoauth2Sasl): void
The third parameter can be disabled by rewriting the DocBlock comment in the `Pop3` sublcass.
The second parameter, the `password` one, can in fact be misleading, but we can write a good DocBlock comment for that too.

Explicitness is a good goal, but keep in mind that:

1. adding a new API represents a huge maintenance cost
2. the `login` API doesn't disappear: this class still has it, and it would be very confusing for the end user to have both API available

@Ocramius WDYT?

2022-08-10 15:18 UTC, griesi007 commented on src/Protocol/Pop3/Xoauth2/Microsoft.php
> +    public function authenticate(string $xoauth2Sasl): void
@Slamdunk Another issue I see with the login method are missing type declarations for the params

2022-08-10 15:55 UTC, griesi007 commented
@Slamdunk I am a bit confused about changes lately in Protocol\Pop3. composer.json specifies that laminas mail should be compatible to PHP7.3 but these changes aren´t "Catching exceptions without capturing them to variables ". Which is minimal required compatibility in laminas-mail?

2022-08-11 06:01 UTC, Slamdunk commented on src/Protocol/Pop3/Xoauth2/Microsoft.php
> +class Microsoft extends \Laminas\Mail\Protocol\Pop3
This is still pending

2022-11-17 08:51 UTC, griesi007 commented
@Slamdunk : what´s the current status on this pull request? All requested changes habe been applied some time ago. Is it still considered to be accepted and merged?

2022-11-17 08:59 UTC, Slamdunk commented
I'm sorry for the late reply, indeed I forgot this.

I don't know how to handle this properly though: I am not able to check that this PR works, I don't have an Office365 account.

@Ocramius @weierophinney beside the formal correctness of the code and adherence to `laminas` standards, is trusting the contributor enough to merge a PR with a new feature, when I cannot test it and its test cannot be automated?

2022-11-17 10:42 UTC, Ocramius commented
@Slamdunk if you are happy with just the unit test, then let's move it forward.

2022-11-18 14:25 UTC, merged