Update laminas-coding-standard to v2
laminas/laminas-mail pull request #202
Opened 2022-08-02 06:55 UTC by Slamdunk

2022-08-02 07:04 UTC, Slamdunk commented
```
PHP Fatal error:  Uncaught TypeError: Argument 5 passed to SlevomatCodingStandard\Helpers\Annotation\ParameterAnnotation::__construct() must be an instance of PHPStan\PhpDocParser\Ast\PhpDoc\ParamTagValueNode or null, instance of PHPStan\PhpDocParser\Ast\PhpDoc\TypelessParamTagValueNode given, called in /github/workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/AnnotationHelper.php on line 357 and defined in /github/workspace/vendor/slevomat/coding-standard/SlevomatCodingStandard/Helpers/Annotation/ParameterAnnotation.php:31
```
:sob:

2022-08-02 07:36 UTC, Ocramius commented
Yup, you can force `phpstan/phpdoc-parser: <1.6` to make it run, meanwhile (do it locally, run a ` composer update`, then remove the clause and use `composer update nothing`)

2022-08-02 07:38 UTC, Slamdunk commented
Wouldn't CI fail nevertheless, if I don't commit the `phpdoc-parser: <1.6` requirement?

2022-08-02 07:42 UTC, Ocramius commented
Only in the next lockfile update PR

2022-08-02 08:49 UTC, Slamdunk commented
As I expected, build can't get green if I don't commit `"phpstan/phpdoc-parser": "~1.5.0"`:
https://github.com/laminas/laminas-mail/runs/7627796218?check_suite_focus=true#step:3:416

I can commit it though, can't I?

2022-08-02 08:51 UTC, Ocramius commented
The idea is to commit a `composer.lock` with an older `phpstan/phpdoc-parser`, by leaving `composer.json` intact.
CS checks run on locked dependencies only.

2022-08-02 08:53 UTC, Slamdunk commented
Oh, now I get it.

But I don't see a laminas guide on how to produce the `composer.lock` consistently: is a `composer update` on lowest supported PHP binary enough?

2022-08-02 08:57 UTC, Ocramius commented
There's no guide for that, afaik: I proposed an approach in https://github.com/laminas/laminas-mail/pull/202#issuecomment-1202127637

 1. add the dependency restriction to `composer.json`
 2. run `composer update`
 3. remove the dependency restriction from `composer.json`
 4. run `composer update nothing`

this gives you a `composer.lock` in the state you need it.

2022-08-02 09:04 UTC, Slamdunk commented
Thank you, I was missing the last step.

Now, down to the PR: LCSv2 introduces `declare(strict_types=1);` everywhere, should this change be considered a BC Break?

2022-08-02 09:21 UTC, Ocramius commented
It really depends - `declare(strict_types=1)` is safe to perform in some cases, while in others, it can lead to massive breakages.

I wouldn't say that the `laminas/laminas-mail` code is very "safe", at least when looking at its large psalm baseline:

https://github.com/laminas/laminas-mail/blob/2ec0498fd03dc4684e24b7c7e0f7d015ebabe6d5/psalm-baseline.xml#L3904-L3908

I think we need to disable that rule here. See how it's done in `laminas/laminas-eventmanager`: 

https://github.com/laminas/laminas-eventmanager/blob/6c056ab3b4b464daa308fd9ca3e7416ca40cf200/phpcs.xml#L23-L25

2022-08-02 13:14 UTC, Slamdunk reviewed
I've carefully fixed all the PHPCS issues.

I've also fixed most of the notable PSalm issues; the rest that I've baselined are just too tedious to be done manually now in PHPDocs.

Similarly to what I've done for [`laminas-form:v3.0.0`](https://github.com/laminas/laminas-form/pulls?q=is%3Apr+author%3ASlamdunk+is%3Aclosed+milestone%3A3.0.0) I'll be happy to clear all PSalm baseline once we can ship native types though.

2022-08-02 13:14 UTC, Slamdunk commented on src/Exception/ExceptionInterface.php
> +interface ExceptionInterface extends Throwable
This is the main relevant change in the Psalm fixing process, it should be BC as far as I know

2022-08-02 13:17 UTC, Ocramius requested changes

2022-08-02 13:17 UTC, Ocramius commented on src/Header/AbstractAddressList.php
> +     * @param bool $format
Wait, the format is not a string? :O

2022-08-02 13:17 UTC, Ocramius commented on src/Header/AbstractAddressList.php
> +     * @param bool $format
One thing we could improve here is documenting `@param HeaderInterface::FORMAT_* $format`, but non-blocker.

2022-08-02 13:17 UTC, Ocramius commented on src/Header/Subject.php
> -        $subject = (string) $subject;
We still need this, even if redundant, for any people passing a non-string `$subject`

2022-08-02 13:17 UTC, Ocramius commented on src/Protocol/Imap.php
> +        $set = (string) $from;
This change is a bit cryptic :thinking:

2022-08-02 13:17 UTC, Ocramius commented on src/Protocol/SmtpPluginManager.php
> +     * @var array<array-key, class-string>
The template parameter on `AbstractPluginManager<InstanceType>` should probably be filled:

https://github.com/laminas/laminas-servicemanager/blob/6cee2f3125e074c0960c13a9ffc1ed93127b860e/src/AbstractPluginManager.php#L35

2022-08-02 13:17 UTC, Ocramius commented on src/Storage/Folder/FolderInterface.php
> +     * @return Folder root or wanted folder
Shouldn't this return `FolderInterface`? Why is the concrete instance returned from the interface?

2022-08-02 13:17 UTC, Ocramius commented on src/Storage/Part.php
> +     * @return string|true|array|HeaderInterface|ArrayIterator value of header in wanted or internal format
Hmm, `true`? :thinking:

2022-08-02 13:29 UTC, Slamdunk commented on src/Storage/Folder/FolderInterface.php
> +     * @return Folder root or wanted folder
This puzzled me too: `FolderInterface` represents a Storage contract (Imap, Mailbox, Maildir) while `Folder` is and actual folder in any of those storage.

2022-08-02 13:31 UTC, Slamdunk commented on src/Storage/Part.php
> +     * @return string|true|array|HeaderInterface|ArrayIterator value of header in wanted or internal format
I didn't follow the rabbit down the hole enough: proper PHPDoc fixing coming

2022-08-02 13:38 UTC, Slamdunk commented on src/Protocol/Imap.php
> +        $set = (string) $from;
`$from` already is an `int`, and it needs to be used as a `string` to compose the proper Imap raw request.

I have no idea why it was the other way, so I guess it was just a typo

2022-08-02 13:47 UTC, Slamdunk commented on src/Header/Subject.php
> -        $subject = (string) $subject;
:+1:

2022-08-02 13:48 UTC, Slamdunk commented on src/Header/AbstractAddressList.php
> +     * @param bool $format
> Wait, the format is not a string? :O

Heh :facepalm: 

> `@param HeaderInterface::FORMAT_*`

:+1:

2022-08-02 14:08 UTC, Slamdunk commented on src/Protocol/SmtpPluginManager.php
> +     * @var array<array-key, class-string>
I've looked at https://github.com/laminas/laminas-validator/pull/129 and commit https://github.com/laminas/laminas-mail/pull/202/commits/d20feb23f9e3806725e6e2d8dc2531cc5c09086c is the result

2022-08-02 14:12 UTC, Slamdunk commented on src/Protocol/SmtpPluginManager.php
> +     * @var array<array-key, class-string>
```
Error: src/Protocol/SmtpPluginManager.php:26:23: InvalidTypeImport: Type alias FactoriesConfigurationType imported from Laminas\ServiceManager\ConfigInterface
```

Because I've checked commit validity against latest deps, but PSalm in CI runs on lowest which misses all the latest types-related releases.

Should I revert this, or keep and baseline it?

2022-08-04 12:04 UTC, Ocramius commented on src/Exception/ExceptionInterface.php
> +interface ExceptionInterface extends Throwable
It's not BC, but then `ExceptionInterface` here is only designed to be **caught**, not **implemented**, so we're OK.

2022-08-04 12:05 UTC, Ocramius commented on src/Header/Subject.php
> -        $subject = (string) $subject;
35aac10461a138f5e53115451857de2bca4cb439

2022-08-04 12:06 UTC, Ocramius commented on src/Header/AbstractAddressList.php
> +     * @param bool $format
e5b23be47d2bb87376e3ddd9656885d33b6decff

2022-08-04 12:07 UTC, Ocramius commented on src/Protocol/Imap.php
> +        $set = (string) $from;
Works for me, thanks!

2022-08-04 12:08 UTC, Ocramius commented on src/Protocol/SmtpPluginManager.php
> +     * @var array<array-key, class-string>
>  but PSalm in CI runs on lowest which misses all the latest types-related releases.

It should run with **locked** dependencies. 

This seems to occur because we're still on PHP 7.3, and the latest type improvements are on PHP 7.4.

Let's touch this in a follow-up that drops PHP 7.4 :+1:

2022-08-04 12:08 UTC, Ocramius commented on src/Storage/Folder/FolderInterface.php
> +     * @return Folder root or wanted folder
Thanks for clarifying! :+1:

2022-08-04 12:09 UTC, Ocramius commented on src/Storage/Folder/FolderInterface.php
> +     * @return Folder root or wanted folder
Related: 88d54cb3d12496a23e731c66e438e09af524123d

2022-08-04 12:10 UTC, Ocramius commented on src/Protocol/SmtpPluginManager.php
> +     * @var array<array-key, class-string>
Ah, I see that you did add the templated types. In order for that to work, we need to drop PHP 7.3, and then a `composer update` **should** bring us on par with the servicemanager improvements, as well as make the build green again  :+1:

2022-08-04 12:10 UTC, Ocramius commented on src/Storage/Part.php
> +     * @return string|true|array|HeaderInterface|ArrayIterator value of header in wanted or internal format
6e6ba8c0819e7aed57a03645306c0df2802d3b1d

2022-08-04 12:11 UTC, Ocramius approved these changes
LGTM.

What's still missing:

 * [ ] drop PHP 7.4
 * [ ] re-generate baseline with the new dependency upgrades (it should get rid of the templated types issues)

2022-08-04 13:24 UTC, Slamdunk commented
> What's still missing

Since you approved this PR, I guess I can merge this as-is (with failing build) and then open a follow up to drop PHP < 8.0.

Merging red builds isn't good, but neither is discussing such big changes in the same PR.
At least that's what I'd do in my repos.

Confirm please, just so that I can learn your preferred way of managing such situations.

2022-08-04 13:27 UTC, Ocramius commented
No, please make it green first, be it through adjusted baseline or else, but let's not merge on red, as that just blocks other work, and will also lead to raised PRs by Renovate bot overnight :|

2022-08-04 13:46 UTC, merged