Drop PHP 7.3 and PHP 7.4 support
laminas/laminas-mail pull request #203
Opened 2022-08-04 14:09 UTC by Slamdunk

2022-08-04 14:10 UTC, Slamdunk commented on composer.json
> -        "zendframework/zend-mail": "*"
https://github.com/zendframework/zend-mail/blob/release-2.10.0/composer.json#L19

Since PHP versions now are going to mismatch completely, we can drop this, can't we?

2022-08-04 14:33 UTC, Ocramius requested changes

2022-08-04 14:33 UTC, Ocramius commented on src/ConfigProvider.php
> -                SmtpPluginManager::class => Protocol\SmtpPluginManager::class,
These should stay for BC, since it may still be referenced by string

2022-08-04 14:33 UTC, Ocramius commented on src/Protocol/SmtpPluginManager.php
> -        'zendmailprotocolsmtp'            => Smtp::class,
These should stay until the next major

2022-08-04 14:33 UTC, Ocramius commented on src/Protocol/SmtpPluginManagerFactory.php
> +use interop\container\containerinterface;
This replacement is wrong due to PHPCS not recognizing `class_alias()`

2022-08-04 14:33 UTC, Ocramius commented on test/Protocol/SmtpPluginManagerFactoryTest.php
> +use interop\container\containerinterface;
This replacement is wrong due to PHPCS not recognizing `class_alias()`

2022-08-05 09:34 UTC, Ocramius approved these changes
:ship: thanks @Slamdunk!

2022-08-05 09:35 UTC, Ocramius commented
@samsonasik I'm gonna hold off a release, if you want to try PHP 8 rector transformations here :-)

2022-08-05 09:35 UTC, merged

2022-08-08 13:49 UTC, weierophinney commented
What was the justification for dropping support for 7.4? Considering it's still receiving security patches, I'm not seeing why we'd drop it in a new minor until later in the year, unless there's some compatibility issue. If there is, it'd be nice to at least have a link so that others coming to the issue know what prompted the decision...

2022-08-08 14:01 UTC, Slamdunk commented
A cascade of dev dep updates lead us to choose either baseline/suppress most of the errors or fix them popping to PHP 8.0.

We are going to support PHP 7.4 on `2.16.x` branch until needed, for security patches only.

2022-08-08 14:36 UTC, Ocramius commented
TBH, dropping PHP version support, especially 7.4, isn't a major problem, since it has only 3 months of shelf life left.


Remember that `2.16.x` will still receive security issues until PHP 7.4 is dead.