Added auth plugin for Xoauth2
laminas/laminas-mail pull request #227
Opened 2023-01-10 23:34 UTC by EmeryEx

- Are you adding something the library currently does not support? Yes
  - Why should it be added? 
     So you can connect to services like Microsoft Office 365 and utilize SMTP that doesn't support legacy protocols
  - What will it enable? 
     Xoauth2 auth protocol for SMTP
  - How will the code be used? 
     via the Laminas\Mail\Protocol\SmtpPluginManager as "xoauth2" or by "connection_class" option as "xoauth2" on SmtpOptions fed into SmtpTransport in a factory

I'm sorry i don't see a develop branch. I'm new to this.

2023-01-10 23:46 UTC, EmeryEx commented
This was a copy of AUTH PLAIN. Some of the checks are not passing for code that is already in the framework in same fashion in another file, but i've tried this on local and it works.

2023-01-11 15:26 UTC, Slamdunk requested changes
I see the Psalm errors are shared among all Auth classes, and you just copy-pasted most of the code.

I'm fine with this, but please update the psalm baseline to get the CI green

2023-01-11 15:26 UTC, Slamdunk commented on src/Protocol/Smtp/Auth/Xoauth2.php
> +    public function __construct($host = '127.0.0.1', $port = null, $config = null)
```suggestion
    public function __construct($host = '127.0.0.1', $port = null, ?array $config = null)
```
Signature should match parent's one

2023-01-11 15:26 UTC, Slamdunk commented on src/Protocol/Smtp/Auth/Xoauth2.php
> +class Xoauth2 extends Smtp
```suggestion
final class Xoauth2 extends Smtp
```

2023-01-18 08:33 UTC, merged

2023-01-18 08:33 UTC, Slamdunk commented
Thank you @EmeryEx

2023-01-18 08:46 UTC, froschdesign commented
@EmeryEx @Slamdunk 
There is a simple rule: what is not documented does not exist!
How can developers discover this and use it without documentation?

_It would be a pity if the work invested here is not used!_

2023-01-18 08:49 UTC, Slamdunk commented
My bad, sorry.

@EmeryEx would you be so kind to update https://github.com/laminas/laminas-mail/blob/2.22.x/docs/book/transport/smtp-authentication.md as well?

2023-01-19 20:49 UTC, EmeryEx commented
Yes I will add doc section in the next week or so when I get some time. Thank you guys!

2023-03-07 10:24 UTC, liowalter commented
Thanks for this @EmeryEx. Could you explain how to use it ? Where do I get the access token ?

2023-03-08 22:50 UTC, EmeryEx commented
> Thanks for this @EmeryEx. Could you explain how to use it ? Where do I get the access token ?

It's no easy task and unfortunately, it's something you need to implement yourself. But once you have the access token with the right permissions, you just have to supply it to SmtpTransport:

`
$transport = new SmtpTransport();

$connection_conf = [
    'username' => $username,
    'access_token' => $token, // the access token you've acquired via an authorization token or refresh token reuest
    'ssl' => 'tls',
];

$options   = new SmtpOptions([
    'name'              => 'example.com',
    'host'              => 'smtp.office365.com',
    'port'              => 587,
    'connection_class'  => 'Xoauth2',
    'connection_config' => $connection_conf,
]);
        
$transport->setOptions($options);
`

Then your transport is ready to send mail.

2023-03-08 23:25 UTC, froschdesign commented
@EmeryEx 
Please create a pull request for it to update the documentation.

2023-03-08 23:27 UTC, EmeryEx commented
> @EmeryEx Please create a pull request for it to update the documentation.

Where exactly should i put it? Not sure the docs flow you've got going on

2023-03-08 23:36 UTC, froschdesign commented
@EmeryEx 
In the documentation you will find a [chapter "SMTP authentication"](https://docs.laminas.dev/laminas-mail/transport/smtp-authentication/), add it there.
The related file can be found in the `docs` folder of this repository:

https://github.com/laminas/laminas-mail/blob/2.22.x/docs/book/transport/smtp-authentication.md

2023-06-18 16:14 UTC, YalagureshJ commented
Hi @EmeryEx, Is this working? Please share the documentation on how to use it?