Type of returning for functions of the prepareSubject and the prepare…
laminas/laminas-mail pull request #241
Opened 2023-05-22 16:31 UTC by artemii-karkusha

Type of returning for functions of the prepareSubject and the prepareParameters have been fixed

#240

2023-05-22 16:33 UTC, Ocramius requested changes
We'd need a test to verify this change: I suppose you expect `getSubject()` to always return a `string`?

2023-05-22 16:44 UTC, Xerkus commented
dockblock and usage checks out, it is expected to always return string.

Return values are passed to `mail()` with signature
```
 mail(
    string $to,
    string $subject,
    string $message,
    array|string $additional_headers = [],
    string $additional_params = ""
): bool
```

2023-05-22 16:49 UTC, Ocramius commented
Yes, I mean a test case (additions to our PHPUnit test suite :D )

The test should fail before this change, and pass after this change.

2023-05-22 19:24 UTC, artemii-karkusha commented
> We'd need a test to verify this change: I suppose you expect `getSubject()` to always return a `string`?

I will add for this case

2023-05-23 09:41 UTC, artemii-karkusha commented
@Ocramius 
Result of test the testAllowMessageWithEmptySubjectButHasBccHeader before changes for SendMail was made. 
<img width="817" alt="Screenshot 2023-05-23 at 11 39 26" src="https://github.com/laminas/laminas-mail/assets/30173454/bc5b1707-40be-4b5e-b4a1-9d53205659fd">

2023-05-23 09:47 UTC, Ocramius requested changes
@artemii-karkusha looking much better now, thanks!

What's missing now is some cleanup around the test case.

2023-05-23 09:47 UTC, Ocramius commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
Is a `RuntimeException` expected to be thrown at all times?

If so, PHPUnit can help you here:

```php
$this->expectException(\RuntimeException::class);
$this->expectExceptionMessage('Something different from a warning');
```

The try-catch can then be removed :)

2023-05-23 09:54 UTC, artemii-karkusha commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
@Ocramius No. It is not expected to throw all time. It was added to be sure logic will not be broken for mailHandler in future.

2023-05-23 14:56 UTC, artemii-karkusha commented
@Ocramius Please let me know if something is needed to changing. It is ready for merging

2023-05-23 14:59 UTC, Ocramius commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
Ok, but then this test has no assertions, and is a risky test :thinking: 

Can we somehow verify the outcome with a valid assertion?

/cc @Slamdunk for ideas

2023-05-23 15:05 UTC, artemii-karkusha commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
It is not real to cover outcome. Function doesn't return nothing. What we can cover is exception which is thrown when someone will change behaviour for subject and it will influence on function the mail(..., #subject). 
prepareSubject which can be better place for test case is protected.
I don't have any ideas how can we cover it in another way. If you have let it will share with me, please.

2023-05-23 15:38 UTC, Ocramius commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
Yep, that's why I poked @Slamdunk to get some more brains :)

2023-05-24 08:20 UTC, Slamdunk commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
IMHO we don't need tests here, it's a type mismatch so getting rid of PSalm suppressions should be enough:

```diff
diff --git a/psalm-baseline.xml b/psalm-baseline.xml
index 88d83696..0140e43e 100644
--- a/psalm-baseline.xml
+++ b/psalm-baseline.xml
@@ -1737,18 +1737,12 @@
     <InvalidArgument>
       <code><![CDATA[[$this, 'handleMailErrors']]]></code>
     </InvalidArgument>
-    <InvalidNullableReturnType>
-      <code>string</code>
-    </InvalidNullableReturnType>
     <MissingReturnType>
       <code>mailHandler</code>
     </MissingReturnType>
     <MixedAssignment>
       <code>$param</code>
     </MixedAssignment>
-    <MixedInferredReturnType>
-      <code>string</code>
-    </MixedInferredReturnType>
     <MixedOperand>
       <code>$param</code>
     </MixedOperand>
diff --git a/src/Transport/Sendmail.php b/src/Transport/Sendmail.php
index aae76f49..58868dda 100644
--- a/src/Transport/Sendmail.php
+++ b/src/Transport/Sendmail.php
@@ -9,6 +9,7 @@ use Laminas\Mail\Transport\Exception\InvalidArgumentException;
 use Laminas\Mail\Transport\Exception\RuntimeException;
 use Traversable;
 
+use function assert;
 use function count;
 use function escapeshellarg;
 use function gettype;
@@ -200,10 +201,12 @@ class Sendmail implements TransportInterface
     {
         $headers = $message->getHeaders();
         if (! $headers->has('subject')) {
-            return;
+            return '';
         }
-        $header = $headers->get('subject');
-        return $header->getFieldValue(HeaderInterface::FORMAT_ENCODED);
+        $header     = $headers->get('subject');
+        $fieldValue = $header->getFieldValue(HeaderInterface::FORMAT_ENCODED);
+        assert(is_string($fieldValue));
+        return $fieldValue;
     }
 
     /**
@@ -259,7 +262,7 @@ class Sendmail implements TransportInterface
     protected function prepareParameters(Mail\Message $message)
     {
         if ($this->isWindowsOs()) {
-            return;
+            return '';
         }
 
         $parameters = (string) $this->parameters;
```

2023-05-24 08:24 UTC, Ocramius commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
I'm happy with this outcome too :+1:

2023-05-24 16:43 UTC, artemii-karkusha commented on test/Transport/SendmailTest.php
> +        } catch (\RuntimeException $runtimeException) {
@Ocramius 
It has to be closed. I did mistake when changed author for commits. I have created new PL with all needed changes. 
https://github.com/laminas/laminas-mail/pull/242

2023-05-25 09:08 UTC, Slamdunk commented
See #242

2023-05-25 09:08 UTC, closed without merging