Type of returning for functions of the prepareSubject and the prepare…
laminas/laminas-mail pull request #242
Opened 2023-05-24 16:41 UTC by artemii-karkusha

Type of returning for functions of the prepareSubject and the prepareParameters have been fixed

https://github.com/laminas/laminas-mail/issues/240

2023-05-24 16:43 UTC, artemii-karkusha commented
@Ocramius 
Suggested changes have been applied.. Test case has been reverted. 
I have change the  Laminas\Mail\Transport\Envelope::getFrom, because of issue with type of property the $from. 
Thank you.

2023-05-25 09:07 UTC, Slamdunk requested changes

2023-05-25 09:07 UTC, Slamdunk commented on psalm-baseline.xml
> -    </InvalidNullableReturnType>
I see you've removed the `InvalidNullableReturnType` from `src/Transport/Envelope.php`, but I rather not touch the Envelope class properties as it could be seen as a BC Break.

In https://github.com/laminas/laminas-mail/pull/241#discussion_r1203676239 the only `InvalidNullableReturnType` removal I suggest is the `src/Transport/Sendmail.php`, which in this PR is still in place

2023-05-25 12:34 UTC, Slamdunk approved these changes

2023-05-25 13:13 UTC, Slamdunk commented
Thank you

2023-05-25 13:15 UTC, merged