Transport\InMemory: no messages could have been sent, fix return type
laminas/laminas-mail pull request #83
Opened 2020-03-27 10:31 UTC by Slamdunk

It may happen that no messages have been sent, so the return type could be null as well.

2020-03-29 20:26 UTC, michalbundyra requested changes
@Slamdunk Just checked, it would be nice to add test case as well. `null` behaviour is currently untested. Thanks!

2020-03-30 07:16 UTC, michalbundyra approved these changes

2020-03-30 07:18 UTC, Slamdunk commented
Mmm, I don't get why DCO fails, my latest commit is signed-off:
![immagine](https://user-images.githubusercontent.com/152236/77885516-6df21100-7267-11ea-81dd-d79e26eb9d14.png)
Do I have to sign-off also the first commit?

2020-03-30 07:24 UTC, michalbundyra commented
@Slamdunk 

> Do I have to sign-off also the first commit?

In the current situation yes, but I've heard that "app update is on the way" to check signoff just on head commit. So if you can signoff the first commit as well, it would be great. See https://github.com/laminas/laminas-mail/pull/83/checks?check_run_id=544640351 for more details.

2020-03-30 08:06 UTC, michalbundyra commented
Thanks, @Slamdunk!

2020-03-30 08:06 UTC, merged